### ISSUE TITLE
数据集的预处理

### ISSUE THREAD

**Issue by SRM2020-0923** [BICLab/ASA-SNN#2]
您方便公布一下，各种数据集的预处理代码嘛？

**Comment by SRM2020-0923** [comment]
原始的DVS_Gesture并没有train和test文件，是需要自己提前mkdir一个train和test文件夹嘛

**Comment by jkhu29** [comment]
数据从aedat文件读取后存入mat或npy即可
train与test分离，gesture文件官网有教程，或可按照spikingjelly做法分离数据集

**Comment by BICLab** [comment]
Please see https://github.com/BICLab/Attention-SNN/issues/7
