### ISSUE TITLE
About gradient calculation of mask operation

### ISSUE THREAD

**Issue by LMMMEng** [BICLab/ASA-SNN#4]
Thank you for your excellent work!

I'm somewhat confused about the gradient calculation of the [mask operation](https://github.com/BICLab/ASA-SNN/blob/c68b2d0211eb481c47af9c43fc2107f057a6066d/models/module/Attn.py#L30). It seems that input of the ```get_im_subim_channels``` function includes channels_im and ```map_add```, while the output is computed by using top-k for ```map_add``` and generates binary mask. So, how does the gradient backward to ```map_add```?  And How are the weights of  ```self.fc``` updated?

**Comment by jkhu29** [comment]
Hi, thanks for your interest. `map_add` is split into two parts and each part has its gradient. This can be visualized as two parallel gradient backward graphs, A and B. The `top-k` is used to select which channels (or time) go through graph A and the rest through graph B.
