### ISSUE TITLE
gait数据集转换

### ISSUE THREAD

**Issue by Antleaf-0921** [BICLab/ASA-SNN#5]
非常感谢贵团队为我学习的领域作出的巨大贡献，我在gait数据集上复现时，发现下载的数据集是txt文件，而代码要求是npy文件，请问应该怎样转换呢，可以公布你们处理的代码吗？

**Comment by Antleaf-0921** [comment]
代码细节中需要的是data.npy和target.npy，这部分是怎么划分的呢？可以公布你们处理的代码吗？

**Comment by BICLab** [comment]
Please see https://github.com/BICLab/Attention-SNN/issues/7

**Comment by JunLi0514** [comment]
非常感谢贵团队的解答，但运行后还存在一些问题，请问可以询问吗？MA_SNN/DVSGait/DVS_gait_data_process/DVS128_Gait_dataloaders.py  里，在 __DVS128_Gait_txt_to_npy__ 函数中，对每个txt文件load后转换为np.array形式并添加到train_data/test_data list中，但是每个txt的行数不一样，train_data/test_data list不能直接转为np.array保存为npy文件，请问是在处理前已经把txt文件裁剪到相同行数了吗？
